### ISSUE TITLE
Car task

### ISSUE THREAD

**Issue by laurafdeza** [laurafdeza/Dissertation#3]
Por ahora tengo sólo una pregunta, la de Slack quizá te la haga más tarde, que ahora estoy mirando esos análisis otra vez.

En la prueba de anticipación visuoespacial tengo dos medidas, desviación en ms y desviación en cm. Tengo que usar las dos? Deduzco que son comparables porque si un participante se pasa 1 s, el coche recorre por ejemplo 1 cm, y si se pasa sólo 0.5 s, será solo 0.5 cm, no? Si con una medida es suficiente, he elegido la de tiempo para ser consistente con el resto de las pruebas.

- raw data: [https://github.com/laurafdeza/Dissertation/tree/master/data/car](url)
- cleaning script: [https://github.com/laurafdeza/Dissertation/blob/master/scripts/cleaning/psychopy_tasks.R](url)
- clean data: [https://github.com/laurafdeza/Dissertation/tree/master/data/clean](url)

@jvcasillas

**Comment by jvcasillas** [comment]
Es una pregunta interesante. Parece que debería haber una correlación casi perfecta entre la medidas. Recomiendo que mires precisamente eso (desviacion_rt ~ desviacion_cm), aunque solo sea para comprobar. Luego te quedas con RT, si es lo que prefieres, y en algún momento puedes dejar una nota a pie de página explicando que dan la misma información.

**Comment by laurafdeza** [comment]
Gracias! Sale una correlación de 0.9471396, así que me quedaré con RT.
