### ISSUE TITLE
Nested models

### ISSUE THREAD

**Issue by laurafdeza** [laurafdeza/Dissertation#5]
Tengo una pregunta conceptual.

Digamos que en el GLMM o en el GCA tengo mi modelo base después de mirar random effects:

```
gca_mod_mon_base <-
  lmer(eLog ~ 1 + (ot1 + ot2 + ot3) +
         (1 + condition_sum + (ot1 + ot2 + ot3) | participant) +
         (1 + ot1 + ot2 + ot3 | target),
       control = lmerControl(optimizer = 'bobyqa', optCtrl = list(maxfun = 3e5)), 
       REML = F,
       data = filter(stress_gc_subset, group == "mon"))
```

Y empiezo a añadir variables:

```
gca_mod_mon_cond_0 <- update(gca_mod_mon_base,   . ~ . + condition_sum)
gca_mod_mon_cond_1 <- update(gca_mod_mon_cond_0,   . ~ . + ot1:condition_sum) 
gca_mod_mon_cond_2 <- update(gca_mod_mon_cond_1,   . ~ . + ot2:condition_sum)
gca_mod_mon_cond_3 <- update(gca_mod_mon_cond_2,   . ~ . + ot3:condition_sum)
```

Y comparo estos modelos y no hay diferencia. Ahora añado otra variable más, por ejemplo WM. El modelo que tomo como referencia, ¿puede ser el base o tiene que ser el último nested model anterior, en este caso gca_mod_mon_cond_3? 

```
gca_mod_mon_wm_0 <- update(gca_mod_mon_base, . ~ . + WM_set)
gca_mod_mon_wm_1 <- update(gca_mod_mon_wm_0,   . ~ . + ot1:WM_set)
...
```

@jvcasillas

**Comment by jvcasillas** [comment]
Normalmente usarías el modelo "base" porque añadir los otros efectos no mejora el fit (o sea para qué dejarlos?). Dicho eso, hay veces en las que quieres un parameter estimate específico teniendo otro efecto en el modelo. Si no es el caso, entonces déjalo fuera.

**Comment by laurafdeza** [comment]
Uy, perdón, por algún motivo no había visto este mensaje. Perfecto!
