### ISSUE TITLE
GCA

### ISSUE THREAD

**Issue by laurafdeza** [laurafdeza/Dissertation#7]
@jgeller112

Hi Jason,

In this repo you'll see many other things related to my dissertation. You can disregard those.

My linguistic data was collected with an eye-tracker and I'm creating the models through growth curve analysis. All scripts related to my first chapter are under "stress" and the ones related to my second chapter are under "music". Whatever concerns both is in a previous level folder.

For my two problems:

1. The graphs from "stress" come out empty.
[This](https://github.com/laurafdeza/Dissertation/blob/master/scripts/stress/analyses/03_analysis_gca.R) is the GCA script and [this](https://github.com/laurafdeza/Dissertation/blob/master/scripts/stress/analyses/06_plots_gca.R) is the plots script. The final model I am using is gca_full_mod_group_3, stored in full_mods_refactor.

2. I'm looking into how our ability to make linguistic predictions is associated to make pitch and rhythmic predictions in "music". So I have basically three dependent variables, but I'm not sure what is the best way to test the relationship. [This script](https://github.com/laurafdeza/Dissertation/blob/master/scripts/music/analyses/03_analysis_gca.R) is what I have tested so far but, to be honest, I know it's not right.
I was thinking about doing a model for each part, so one for speech, one for pitch and one for rhythm and then compare them through a MANOVA, or including all three dependent variables in [multivariate multiple regression](https://data.library.virginia.edu/getting-started-with-multivariate-multiple-regression/).

The variable for speech is proportion of fixations on target, and the rhythm and pitch data is continuous, as they are measuring time.

Other than that, my predictors are group and condition (present vs preterit) in "stress". In "music" the time measurements come from different conditions as well. The difference is that in the linguistic task participants were exposed only to one condition, but in the non-linguistic tasks they were presented all conditions.

Let me know what should be explained more clearly or if you need any other piece of information.

Thank you!

**Comment by jgeller112** [comment]
1. The graphs from "stress" come out empty.
This is the GCA script and this is the plots script. The final model I am using is gca_full_mod_group_3, stored in full_mods_refactor.


You did not denote you wanted a line aesthetic (I commented where that needs to be). You also need to make sure you are extracting the mean prop fix for each P. This can be called with the stat_summary function below. Moreover, I am kind of picky about this (take it or leave it), but you should be calculating within-subject CIs. 

```
stress_p1 <- stress50 %>%        
  na.omit(.) %>%
  filter(., time_zero >= -10, time_zero <= 20) %>%
  mutate(., group = fct_relevel(group, "mon", "aes", "ies", "ams", "ims")) %>%
  ggplot(., aes(x = time_zero, y = target_prop, fill = group, shape = group)) +
  facet_grid(. ~ cond) + 
  geom_hline(yintercept = 0.5, color = 'white', size = 3) +
  geom_vline(xintercept = 0, color = 'grey40', lty = 3) +
  geom_vline(xintercept = 4, color = 'grey40', lty = 3) +
  stat_summary(fun.y = "mean", geom = "line", size = 1) + # you did not denote the aesthetic (line, bar) you wanted. This function #will computer the mean for Prob Fix
  stat_summary(fun.data = mean_cl_boot, geom = 'pointrange', size = 0.5,
               stroke = 0.5, pch = 21) +
  scale_fill_brewer(palette = 'Set1', name = "",
                    labels = c("mon", "aes", "ies", "ams", "ims")) +
  scale_x_continuous(breaks = c(-10, 0, 10, 20),
                     labels = c("-500", "0", "500", "1000")) +
  labs(y = 'Proportion of target fixations',
       x = 'Time relative to target syllable offset (ms)',
       caption = "Mean +/- 95% CI") +
  annotate("text", x = 3.3, y = 0.02, label = '200ms',
           angle = 90, size = 3, hjust = 0) +
  theme_bw()
```

![laura_fig](https://user-images.githubusercontent.com/18429968/93796398-c992cb00-fc08-11ea-8f29-0b1ec65fae8f.png)

**Comment by laurafdeza** [comment]
That's awesome. Thank you!

In that same script I have two more issues with the plot after.
One is about geom_ribbon. If it is uncommented, the console says "Error: Aesthetics can not vary with a ribbon": 

`
stress_p2 <- model_preds$fits_all %>%

    mutate(condition = if_else(condition_sum == 1, "Present", "Preterit"),
         condition = fct_relevel(condition, "Present")) %>%

    ggplot(., aes(x = time_zero, y = fit, ymax = ymax, ymin = ymin,
                fill = condition_sum, color = condition_sum)) +

    facet_grid(group ~ .) +

    geom_hline(yintercept = 0, lty = 3, size = 0.4) +

    geom_vline(xintercept = 4, lty = 3, size = 0.4) +

    geom_ribbon(alpha = 0.2, color = NA, show.legend = F) +                 # this is the problematic line

    geom_line(size = 0.75) +

    geom_point(aes(color = condition_sum), size = 1.3, show.legend = F) +

    geom_point(aes(color = condition_sum), size = 0.85, show.legend = F) +

    scale_x_continuous(breaks = c(-4, 0, 4, 8, 12),
                     labels = c("-200", "0", "200", "400", "600")) +

    labs(x = "Time (ms) relative to target syllable offset",
       y = "Empirical logit of looks to target") +

    theme_big + legend_adj
`

When geom_ribbon is commented, the plot displayed is the one below. Do you think the problem with geom_ribbon might be related to the line not being continuous?
![stress_p2](https://user-images.githubusercontent.com/38184931/93808088-8bea6e00-fc19-11ea-9e52-89b6628f658d.png)

**Comment by jgeller112** [comment]
```
geom_ribbon(alpha = 0.2, color = NA, show.legend = F)

```


You need to pass some summary data into the function. 

```
# Plot GCA --------------------------------------------------------------------

# Within group differences
stress_p2 <- model_preds$fits_all %>%
  mutate(condition = if_else(condition_sum == 1, "Present", "Preterit"),
         condition = fct_relevel(condition, "Present")) %>%
  ggplot(., aes(x = time_zero, y = fit, ymax = ymax, ymin = ymin,
                fill = condition, color = condition)) +
  facet_wrap(group ~ .) +
  geom_hline(yintercept = 0, lty = 3, size = 0.4) +
  geom_vline(xintercept = 4, lty = 3, size = 0.4) +
  stat_summary(fun.y = "mean", geom = "line", size = 1) + # you did not denote the asthetic (line, bar) you wanted. This function will computer the mean for Prob Fix
  stat_summary(fun.data = mean_cl_boot, geom = 'ribbon',fun.args=list(conf.int=0.95),
               alpha = 0.5) + 
  geom_point(aes(color = condition), size = 1.3, show.legend = F) +
  geom_point(aes(color = condition), size = 0.85, show.legend = F) +
  scale_x_continuous(breaks = c(-4, 0, 4, 8, 12),
                     labels = c("-200", "0", "200", "400", "600")) +
  # scale_color_brewer(palette = "Set1", name = "Syllable structure") +
  labs(x = "Time (ms) relative to target syllable offset",
       y = "Empirical logit of looks to target") +
  theme_big + legend_adj
```
![laura_rib](https://user-images.githubusercontent.com/18429968/93814351-69a91e00-fc22-11ea-934d-d72fdbe71a27.png)

**Comment by jgeller112** [comment]
```
I'm looking into how our ability to make linguistic predictions is associated to make pitch and rhythmic predictions in "music". So I have basically three dependent variables, but I'm not sure what is the best way to test the relationship. This script is what I have tested so far but, to be honest, I know it's not right.
I was thinking about doing a model for each part, so one for speech, one for pitch and one for rhythm and then compare them through a MANOVA, or including all three dependent variables in multivariate multiple regression.

```


I took a look at your analysis script. Why do you think it is incorrect? I honestly think that including pitch and rhythmic predictors into the model is the correct solution. Using a MANOVA will essentially tell you the same things as running separate statistical models for each DV--it will not tell you how the DVs are related. 

I have no idea what your design is nor do I have a clear explanation of all your variables of interest so I might be mistaken, but your analysis strategy seems reasonable to me.  That is, a model that includes pitch and rhythmic fixed effects along with interactions between orthogonal time terms and other variables of interest as a predictor of empirical log. Does this make sense?

**Comment by laurafdeza** [comment]
Thank you about the graphs! 

My design is:
- Group: 5 possible groups (Spanish speakers, English speakers, and Mandarin Chinese speakers). This predictor is categorical.
- Condition/stress: this refers to the linguistic eye-tracking task (visual-world paradigm). Here participants were exposed either a "stressed" condition or "unstressed" condition. In total each participant was presented 8 of each, but never of the same pair. Here I'm looking at proportion of fixations.
- WM: (Operation span task) I'm still thinking what to do with it. The English speakers have overall the highest WM and the Spanish WM the lowest. Like, English speakers are around the 10-12 score and Spansh speakers around the 5-7, and the Mandarin in between. These data align with previous WM literature.  If I include it, I'm trying to find some kind of normalizing test. This predictor is continuous.
- Pitch: (similar to a melody discrimination task, but here instead of comparing two melodies, they compared new tones to the tones previously heard in the same. melody) there were 5 levels to which all participants were exposed. In each level the distance between the tones the participants were hearing was different. Say, in DO_up the distance was half a tone. In MI_up was one tone, and in SOL_up it was a tone and a half. And then _up means the melody grew higher in pitch and _down it grew lower. The data collected is continuous, as the task was measuring reaction time, basically.
- Rhythm: (imperative tone task, participants needed to tap on the tone following the imperative tone task, which sounded different from the rest) there were four different beat patterns and all participants completed trials for all of them. This measure is also continuous, as the data referred to how close to or far from the onset of the tap-along beat the tap happened in time.

I was just wondering because if I include all the possible conditions for pitch (6) and rhythm (4) the number of IV is huge, so I'd like to keep the model as simple as possible. Since each of the different conditions do not seem to have much effect except for a couple of them, maybe I could just merge all pitch conditions and all rhythmic conditions to have two general predictors, pitch and rhythm?

**Comment by jgeller112** [comment]
If you can come up with a meaningful overall measure of pitch and rhythm that would be preferable. 



Jason Geller, Ph.D.
Research Programmer
RuCCS, The Center for Cognitive Science
152 Frelinghuysen Road<https://www.google.com/maps/search/152+Frelinghuysen+Road?entry=gmail&source=g>, A122, Busch Campus
Piscataway, New Jersey 08854
Email: Jason.geller@ruccs.rutgers.edu

On Sep 22, 2020, at 8:38 AM, Laura Fernández Arroyo <notifications@github.com> wrote:

﻿

Thank you about the scripts!

My design is:

  *   Group: 5 possible groups (Spanish speakers, English speakers, and Mandarin Chinese speakers). This predictor is categorical.
  *   Condition/stress: this refers to the linguistic eye-tracking task (visual-world paradigm). Here participants were exposed either a "stressed" condition or "unstressed" condition. In total each participant was presented 8 of each, but never of the same pair. Here I'm looking at proportion of fixations.
  *   WM: (Operation span task) I'm still thinking what to do with it. The English speakers have overall the highest WM and the Spanish WM the lowest. Like, English speakers are around the 10-12 score and Spansh speakers around the 5-7, and the Mandarin in between. These data align with previous WM literature. If I include it, I'm trying to find some kind of normalizing test. This predictor is continuous.
  *   Pitch: (similar to a melody discrimination task, but here instead of comparing two melodies, they compared new tones to the tones previously heard in the same. melody) there were 5 levels to which all participants were exposed. In each level the distance between the tones the participants were hearing was different. Say, in DO_up the distance was half a tone. In MI_up was one tone, and in SOL_up it was a tone and a half. And then _up means the melody grew higher in pitch and _down it grew lower. The data collected is continuous, as the task was measuring reaction time, basically.
-Rhythm: (imperative tone task, participants needed to tap on the tone following the imperative tone task, which sounded different from the rest) there were four different beat patterns. This measure is also continuous, as the data referred to how close to or far from the onset of the tap-along beat the tap happened in time.

I was just wondering because if I include all the possible conditions for pitch (6) and rhythm (4) the number of IV is huge, so I'd like to keep the model as simple as possible. Since each of the different conditions do not seem to have much effect except for a couple of them, maybe I could just merge all pitch conditions and all rhythmic conditions to have two general predictors, pitch and rhythm?
